name: flutter_ios_calculator
description: An iOS Calculator replica built with Flutter.
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  auto_size_text: ^3.0.0
  provider: ^6.1.5
  touch_interceptor: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: font/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: font/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: font/SF-Pro-Display-Light.otf
          weight: 200
        - asset: font/SF-Pro-Display-Thin.otf
          weight: 100
